# Assignment 07

this assignment was copied from: https://github.com/wcj365/python-stats-dataviz/blob/master/assignments/assignment_07.ipynb

### Note:
- For visualization, you have the freedom to choose one or many from
    - Matplotlib
    - Seaborn
    - Plotly Express 
    - any other library
- You can use the local Jupyter environment if you are not comfortable with Colab for this assignment.
- Use use this notebook as your template and follow the instructions

The first half of this assignment is a repeat of assignment 05.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

You will unzip the zip file manually in preparation for this assignment.

The links to the zip file is (you have already used it in your assignment 5):

- https://data.ed.gov/dataset/college-scorecard-all-data-files-through-6-2020/resources (The page containing link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_01192021.zip (The link to download the zip file)

After unzipping, You will have all files in one folder named "CollegeScorecard_Raw_Data" 

The folder contains the yearly data files from 1996 to 2019 school years.

if you are using your local environment, I suggest you create a new folder call "Assignment7" and place the Notebook file and the data folder under it.
```
Assignment7/
    - assignment_07.ipynb
    - CollegeScorecard_Raw_Data/
        - ...
        - 'MERGED1996_97_PP.csv',
        - 'MERGED2015_16_PP.csv',
        - ...
        - 'MERGED2017_18_PP.csv'
```


## <1> 
#### Import libraries


In [ ]:
import os
import random
import pandas as pd
import plotly.express as px


## <2> 

**Display the current workin directory using os.getcwd()**

You'll need to import a standard Python library called os (which stands for operating system), so place that import statement in the previous cell.
Since your notebook and your data files are not in the same folder, you want to make sure what is the current working folder and how to access a data file in a different folder


In [ ]:
cwd = os.getcwd()


Crosswalks.zip			  MERGED2006_07_PP.csv
data.yaml			  MERGED2007_08_PP.csv
FieldOfStudyData1415_1516_PP.csv  MERGED2008_09_PP.csv
FieldOfStudyData1516_1617_PP.csv  MERGED2009_10_PP.csv
FieldOfStudyData1617_1718_PP.csv  MERGED2010_11_PP.csv
MERGED1996_97_PP.csv		  MERGED2011_12_PP.csv
MERGED1997_98_PP.csv		  MERGED2012_13_PP.csv
MERGED1998_99_PP.csv		  MERGED2013_14_PP.csv
MERGED1999_00_PP.csv		  MERGED2014_15_PP.csv
MERGED2000_01_PP.csv		  MERGED2015_16_PP.csv
MERGED2001_02_PP.csv		  MERGED2016_17_PP.csv
MERGED2002_03_PP.csv		  MERGED2017_18_PP.csv
MERGED2003_04_PP.csv		  MERGED2018_19_PP.csv
MERGED2004_05_PP.csv		  Most-Recent-Cohorts-All-Data-Elements.csv
MERGED2005_06_PP.csv		  Most-Recent-Cohorts-Field-of-Study.csv


## <3> 
The _os_ library has a method call listdir which generates a list of files in a directory/folder.Use this method to assign the contents (list of file names) of the data folder to a variable and display it.

    You can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder


In [ ]:

#(Write code here)


path = '/datasets/collegedata/'
dir_data = os.listdir(path)
dir_data.sort()
dir_data


['Crosswalks.zip',
 'FieldOfStudyData1415_1516_PP.csv',
 'FieldOfStudyData1516_1617_PP.csv',
 'FieldOfStudyData1617_1718_PP.csv',
 'MERGED1996_97_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2001_02_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED2006_07_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED2018_19_PP.csv',
 'Most-Recent-Cohorts-All-Data-Elements.csv',
 'Most-Recent-Cohorts-Field-of-Study.csv',
 'data.yaml']

## <4> 

The folder contains files that are not the yearly data files
write code to remove the unwanted files from the list vsriable 
Note: don't remove/delete these files from the folder in your drive
For example, use the file extension to only keep the csv files 
or use the name patter - data file name begins with "MERGED"
You can use the concept of list comprehension to write just 
one line of code as well as using a for loop, your choice.

In [ ]:
files = [file for file in dir_data if "MER" in file]
files

['MERGED1996_97_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2001_02_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED2006_07_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED2018_19_PP.csv']

## <5> 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: 

\["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"\].

You should use "usecols" option of Pandas to avoid reading unwanted columns. 

You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer if you use scatter plot, the YEAR needs to be converted to integer or float. 
 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.
Note: this exercise incorporates many techques we learned before
 - list (creating an empty, append an item to the list)
 - for loop 
 - read only the needed columns from a file (using usecols option)
 - add a new column to a data frame
 - concatenate multiple dataframes into a single one
This exercise may appear a big challenging but it worths the effort. You will learn a lot and  love it. I promise.

In [ ]:
frames = []

for filename in files:
    temp_df = pd.read_csv(path + filename, 
                usecols = ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
    temp_df['YEAR'] = filename[6:10]
    frames.append(temp_df)

df = pd.concat(frames)

df

UNITID                                    INSTNM STABBR  REGION  \
0       100636        Community College of the Air Force     AL     0.0   
1       100654                  Alabama A & M University     AL     5.0   
2       100663       University of Alabama at Birmingham     AL     5.0   
3       100672    ALABAMA AVIATION AND TECHNICAL COLLEGE     AL     5.0   
4       100690                        Amridge University     AL     5.0   
...        ...                                       ...    ...     ...   
6801  48511112         Georgia Military College - Dublin     GA     5.0   
6802  48511113        Georgia Military College - Eastman     GA     5.0   
6803  48616901  American College of Barbering - Florence     KY     5.0   
6804  49005401      HCI College - Fort Lauderdale Campus     FL     5.0   
6805  49146401          ABC Adult School - Cabrillo Lane     CA     8.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
0          NaN            NaN  1996  
1          NaN            NaN  1996  
2          NaN            NaN  1996  
3          NaN            NaN  1996  
4          NaN            NaN  1996  
...        ...            ...   ...  
6801       NaN         6120.0  2018  
6802       NaN         6120.0  2018  
6803       NaN            NaN  2018  
6804       NaN        21420.0  2018  
6805       NaN            NaN  2018  

[163331 rows x 7 columns]

## <6> 

Explore the new dataframe (# of observations, varibles, head, tail, sample, missing values, statistics,etc.)

    .shape # show the number of: (rows, columns)
    .info() # general summary of data
    .head() # show first five rows
    .tail() # show last five rows
    .sample(5) # randomly sample 5 data points
    DATAFRAME[DATAFRAME.isna().any(axis=1)] # find and display any null data
    DATAFRAME[['ADM_RATE', 'TUITIONFEE_IN']].describe() # overall statistics for each (other columns are omitted here because they dont contain numerical data)

In [ ]:
df.shape # show the number of: (rows, columns)

(163331, 7)

In [ ]:
df.info() # general summary of data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163331 entries, 0 to 6805
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   UNITID         163331 non-null  int64  
 1   INSTNM         163331 non-null  object 
 2   STABBR         163331 non-null  object 
 3   REGION         163330 non-null  float64
 4   ADM_RATE       44912 non-null   float64
 5   TUITIONFEE_IN  79195 non-null   float64
 6   YEAR           163331 non-null  object 
dtypes: float64(3), int64(1), object(3)
memory usage: 14.0+ MB


In [ ]:
df.head() # show first five rows


UNITID                                  INSTNM STABBR  REGION  ADM_RATE  \
0  100636      Community College of the Air Force     AL     0.0       NaN   
1  100654                Alabama A & M University     AL     5.0       NaN   
2  100663     University of Alabama at Birmingham     AL     5.0       NaN   
3  100672  ALABAMA AVIATION AND TECHNICAL COLLEGE     AL     5.0       NaN   
4  100690                      Amridge University     AL     5.0       NaN   

   TUITIONFEE_IN  YEAR  
0            NaN  1996  
1            NaN  1996  
2            NaN  1996  
3            NaN  1996  
4            NaN  1996

In [ ]:
df.tail() # show last five rows


UNITID                                    INSTNM STABBR  REGION  \
6801  48511112         Georgia Military College - Dublin     GA     5.0   
6802  48511113        Georgia Military College - Eastman     GA     5.0   
6803  48616901  American College of Barbering - Florence     KY     5.0   
6804  49005401      HCI College - Fort Lauderdale Campus     FL     5.0   
6805  49146401          ABC Adult School - Cabrillo Lane     CA     8.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
6801       NaN         6120.0  2018  
6802       NaN         6120.0  2018  
6803       NaN            NaN  2018  
6804       NaN        21420.0  2018  
6805       NaN            NaN  2018

In [ ]:
df.sample(5) # randomly sample 5 data points


UNITID                                     INSTNM STABBR  REGION  \
1950    164085  Maryland University of Integrative Health     MD     2.0   
663     128498                    Albertus Magnus College     CT     1.0   
6761  12468107                                UEI College     CA     8.0   
6260    458779                    Globe University-Wausau     WI     3.0   
3625    212443           Evangelical Theological Seminary     PA     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
1950       NaN            NaN  2000  
663      0.866        26294.0  2011  
6761       NaN            NaN  2005  
6260       NaN        14040.0  2015  
3625       NaN            NaN  2004

In [ ]:
df[df.isna().any(axis=1)] # find and display any null data


UNITID                                    INSTNM STABBR  REGION  \
0       100636        Community College of the Air Force     AL     0.0   
1       100654                  Alabama A & M University     AL     5.0   
2       100663       University of Alabama at Birmingham     AL     5.0   
3       100672    ALABAMA AVIATION AND TECHNICAL COLLEGE     AL     5.0   
4       100690                        Amridge University     AL     5.0   
...        ...                                       ...    ...     ...   
6801  48511112         Georgia Military College - Dublin     GA     5.0   
6802  48511113        Georgia Military College - Eastman     GA     5.0   
6803  48616901  American College of Barbering - Florence     KY     5.0   
6804  49005401      HCI College - Fort Lauderdale Campus     FL     5.0   
6805  49146401          ABC Adult School - Cabrillo Lane     CA     8.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
0          NaN            NaN  1996  
1          NaN            NaN  1996  
2          NaN            NaN  1996  
3          NaN            NaN  1996  
4          NaN            NaN  1996  
...        ...            ...   ...  
6801       NaN         6120.0  2018  
6802       NaN         6120.0  2018  
6803       NaN            NaN  2018  
6804       NaN        21420.0  2018  
6805       NaN            NaN  2018  

[125241 rows x 7 columns]

In [ ]:
df[['ADM_RATE', 'TUITIONFEE_IN']].describe() # overall statistics for each (other columns are omitted here because they dont contain numerical data)

ADM_RATE  TUITIONFEE_IN
count  44912.000000   79195.000000
mean       0.692951   11665.636871
std        0.217058    9986.003542
min        0.000000       0.000000
25%        0.555075    3776.000000
50%        0.717500    9285.000000
75%        0.857100   16148.000000
max        1.000000   74787.000000

## <7>

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC
save the UMBC data to a new data frame. 

Use a new variable so that the old big data frame is still available for later use.


In [ ]:
df.loc[df['INSTNM'].str.contains('Baltimore County', case=False)]

UNITID                                             INSTNM STABBR  \
2116  162098  COMMUNITY COLLEGE OF BALTIMORE COUNTY-CATONSVILLE     MD   
2124  162399      COMMUNITY COLLEGE OF BALTIMORE COUNTY-DUNDALK     MD   
2125  162478        COMMUNITY COLLEGE OF BALTIMORE COUNTY-ESSEX     MD   
2151  163268            University of Maryland-Baltimore County     MD   
2017  162098  COMMUNITY COLLEGE OF BALTIMORE COUNTY-CATONSVILLE     MD   
2025  162399      COMMUNITY COLLEGE OF BALTIMORE COUNTY-DUNDALK     MD   
2026  162478        COMMUNITY COLLEGE OF BALTIMORE COUNTY-ESSEX     MD   
2049  163268            University of Maryland-Baltimore County     MD   
1951  162098  COMMUNITY COLLEGE OF BALTIMORE COUNTY-CATONSVILLE     MD   
1959  162399      COMMUNITY COLLEGE OF BALTIMORE COUNTY-DUNDALK     MD   
1960  162478        COMMUNITY COLLEGE OF BALTIMORE COUNTY-ESSEX     MD   
1982  163268            University of Maryland-Baltimore County     MD   
1924  162098  COMMUNITY COLLEGE OF BALTIMORE COUNTY-CATONSVILLE     MD   
1932  162399      COMMUNITY COLLEGE OF BALTIMORE COUNTY-DUNDALK     MD   
1933  162478        COMMUNITY COLLEGE OF BALTIMORE COUNTY-ESSEX     MD   
1955  163268            University of Maryland-Baltimore County     MD   
1926  163268            University of Maryland-Baltimore County     MD   
6474  434672              Community College of Baltimore County     MD   
1915  163268            University of Maryland-Baltimore County     MD   
6410  434672              Community College of Baltimore County     MD   
1893  163268            University of Maryland-Baltimore County     MD   
6247  434672              Community College of Baltimore County     MD   
1873  163268            University of Maryland-Baltimore County     MD   
6128  434672              Community College of Baltimore County     MD   
1830  163268            University of Maryland-Baltimore County     MD   
5970  434672              Community College of Baltimore County     MD   
1819  163268            University of Maryland-Baltimore County     MD   
5921  434672              Community College of Baltimore County     MD   
1799  163268            University of Maryland-Baltimore County     MD   
5865  434672              Community College of Baltimore County     MD   
1779  163268            University of Maryland-Baltimore County     MD   
5772  434672              Community College of Baltimore County     MD   
1767  163268            University of Maryland-Baltimore County     MD   
5704  434672              Community College of Baltimore County     MD   
1745  163268            University of Maryland-Baltimore County     MD   
5645  434672              Community College of Baltimore County     MD   
1710  163268            University of Maryland-Baltimore County     MD   
5591  434672              Community College of Baltimore County     MD   
1694  163268            University of Maryland-Baltimore County     MD   
5550  434672              Community College of Baltimore County     MD   
1660  163268            University of Maryland-Baltimore County     MD   
5466  434672              Community College of Baltimore County     MD   
1629  163268            University of Maryland-Baltimore County     MD   
5373  434672              Community College of Baltimore County     MD   
1610  163268            University of Maryland-Baltimore County     MD   
5263  434672              Community College of Baltimore County     MD   
1555  163268            University of Maryland-Baltimore County     MD   
5105  434672              Community College of Baltimore County     MD   
1510  163268            University of Maryland-Baltimore County     MD   
4877  434672              Community College of Baltimore County     MD   
1478  163268            University of Maryland-Baltimore County     MD   
4762  434672              Community College of Baltimore County     MD   
1415  163268            University of Maryland-Baltimore County     MD   
4553  4346

In [ ]:
df_umbc = df.query('INSTNM == "University of Maryland-Baltimore County"')
df_umbc

UNITID                                   INSTNM STABBR  REGION  \
2151  163268  University of Maryland-Baltimore County     MD     2.0   
2049  163268  University of Maryland-Baltimore County     MD     2.0   
1982  163268  University of Maryland-Baltimore County     MD     2.0   
1955  163268  University of Maryland-Baltimore County     MD     2.0   
1926  163268  University of Maryland-Baltimore County     MD     2.0   
1915  163268  University of Maryland-Baltimore County     MD     2.0   
1893  163268  University of Maryland-Baltimore County     MD     2.0   
1873  163268  University of Maryland-Baltimore County     MD     2.0   
1830  163268  University of Maryland-Baltimore County     MD     2.0   
1819  163268  University of Maryland-Baltimore County     MD     2.0   
1799  163268  University of Maryland-Baltimore County     MD     2.0   
1779  163268  University of Maryland-Baltimore County     MD     2.0   
1767  163268  University of Maryland-Baltimore County     MD     2.0   
1745  163268  University of Maryland-Baltimore County     MD     2.0   
1710  163268  University of Maryland-Baltimore County     MD     2.0   
1694  163268  University of Maryland-Baltimore County     MD     2.0   
1660  163268  University of Maryland-Baltimore County     MD     2.0   
1629  163268  University of Maryland-Baltimore County     MD     2.0   
1610  163268  University of Maryland-Baltimore County     MD     2.0   
1555  163268  University of Maryland-Baltimore County     MD     2.0   
1510  163268  University of Maryland-Baltimore County     MD     2.0   
1478  163268  University of Maryland-Baltimore County     MD     2.0   
1415  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
2151       NaN            NaN  1996  
2049       NaN            NaN  1997  
1982       NaN            NaN  1998  
1955       NaN            NaN  1999  
1926       NaN         5490.0  2000  
1915    0.6551         5910.0  2001  
1893    0.6327         6362.0  2002  
1873    0.5757         7388.0  2003  
1830    0.7014         8020.0  2004  
1819    0.7143         8520.0  2005  
1799    0.7153         8622.0  2006  
1779    0.6895         8708.0  2007  
1767    0.7174         8780.0  2008  
1745    0.6890         8872.0  2009  
1710    0.6589         9171.0  2010  
1694    0.6081         9467.0  2011  
1660    0.6035         9764.0  2012  
1629    0.6315        10068.0  2013  
1610    0.5961        10384.0  2014  
1555    0.5942        11006.0  2015  
1510    0.5683        11264.0  2016  
1478    0.6021        11518.0  2017  
1415    0.5794        11778.0  2018

## <8>

Explore this UMBC dataframe (# of observations, varibles, head, tail, sample, missing values, statistics,etc.)

    .shape # show the number of: (rows, columns)
    .info() # general summary of data
    .head() # show first five rows
    .tail() # show last five rows
    .sample(5) # randomly sample 5 data points
    DATAFRAME[DATAFRAME.isna().any(axis=1)] # find and display any null data
    DATAFRAME[['ADM_RATE', 'TUITIONFEE_IN']].describe() # overall statistics for each (other columns are omitted here because they dont contain numerical data)

In [ ]:
df_umbc.shape # show the number of: (rows, columns)

(23, 7)

In [ ]:
df_umbc.info() # general summary of data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 2151 to 1415
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   UNITID         23 non-null     int64  
 1   INSTNM         23 non-null     object 
 2   STABBR         23 non-null     object 
 3   REGION         23 non-null     float64
 4   ADM_RATE       18 non-null     float64
 5   TUITIONFEE_IN  19 non-null     float64
 6   YEAR           23 non-null     object 
dtypes: float64(3), int64(1), object(3)
memory usage: 1.4+ KB


In [ ]:
df_umbc.head() # show first five rows

UNITID                                   INSTNM STABBR  REGION  \
2151  163268  University of Maryland-Baltimore County     MD     2.0   
2049  163268  University of Maryland-Baltimore County     MD     2.0   
1982  163268  University of Maryland-Baltimore County     MD     2.0   
1955  163268  University of Maryland-Baltimore County     MD     2.0   
1926  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
2151       NaN            NaN  1996  
2049       NaN            NaN  1997  
1982       NaN            NaN  1998  
1955       NaN            NaN  1999  
1926       NaN         5490.0  2000

In [ ]:
df_umbc.tail() # show last five rows

UNITID                                   INSTNM STABBR  REGION  \
1610  163268  University of Maryland-Baltimore County     MD     2.0   
1555  163268  University of Maryland-Baltimore County     MD     2.0   
1510  163268  University of Maryland-Baltimore County     MD     2.0   
1478  163268  University of Maryland-Baltimore County     MD     2.0   
1415  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
1610    0.5961        10384.0  2014  
1555    0.5942        11006.0  2015  
1510    0.5683        11264.0  2016  
1478    0.6021        11518.0  2017  
1415    0.5794        11778.0  2018

In [ ]:
df_umbc.sample(5) # randomly sample 5 data points

UNITID                                   INSTNM STABBR  REGION  \
1819  163268  University of Maryland-Baltimore County     MD     2.0   
1478  163268  University of Maryland-Baltimore County     MD     2.0   
1915  163268  University of Maryland-Baltimore County     MD     2.0   
1767  163268  University of Maryland-Baltimore County     MD     2.0   
2049  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
1819    0.7143         8520.0  2005  
1478    0.6021        11518.0  2017  
1915    0.6551         5910.0  2001  
1767    0.7174         8780.0  2008  
2049       NaN            NaN  1997

In [ ]:
df_umbc[df_umbc.isna().any(axis=1)] # find and display any null data

UNITID                                   INSTNM STABBR  REGION  \
2151  163268  University of Maryland-Baltimore County     MD     2.0   
2049  163268  University of Maryland-Baltimore County     MD     2.0   
1982  163268  University of Maryland-Baltimore County     MD     2.0   
1955  163268  University of Maryland-Baltimore County     MD     2.0   
1926  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  
2151       NaN            NaN  1996  
2049       NaN            NaN  1997  
1982       NaN            NaN  1998  
1955       NaN            NaN  1999  
1926       NaN         5490.0  2000

In [ ]:
df_umbc[['ADM_RATE', 'TUITIONFEE_IN']].describe() # overall statistics for each (other columns are omitted here because they dont contain numerical data)

ADM_RATE  TUITIONFEE_IN
count  18.000000      19.000000
mean    0.640694    9004.842105
std     0.052728    1825.795421
min     0.568300    5490.000000
25%     0.597600    8270.000000
50%     0.632100    8872.000000
75%     0.689375   10226.000000
max     0.717400   11778.000000

## <9> 
Plot UMBC's in-state tution overtime from 1996 to 2019 using Bar Chart


In [ ]:
fig_instate_bar = px.bar(df_umbc,
                    x= 'YEAR',
                    y='TUITIONFEE_IN'
                    )

fig_instate_bar.show()

## <10> 
Plot UMBC's in-state tution overtime from 1996 to 2019 using Line Chart


In [ ]:
fig_instate = px.line(df_umbc,
                    x= 'YEAR',
                    y='TUITIONFEE_IN'
                    )

fig_instate.show()

## <11>
Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year.

First convert the TUITIONFEE_IN column to a Python List

In [ ]:
umbc_tuition = df_umbc['TUITIONFEE_IN'].tolist()
umbc_tuition

[nan,
 nan,
 nan,
 nan,
 5490.0,
 5910.0,
 6362.0,
 7388.0,
 8020.0,
 8520.0,
 8622.0,
 8708.0,
 8780.0,
 8872.0,
 9171.0,
 9467.0,
 9764.0,
 10068.0,
 10384.0,
 11006.0,
 11264.0,
 11518.0,
 11778.0]

Loop through the list and calculate the % change each year over the prior year
This takes some effort. Not hard, just some abstract/logical thinking and some experiments
Have fun on this one

In [ ]:
prev_tuition = 0
umbc_tuition_change = []

for cost in umbc_tuition:
    if cost == cost:
        if prev_tuition == 0:
            prev_tuition = cost
        umbc_pctchange = ((cost - prev_tuition)/prev_tuition) * 100
        umbc_tuition_change.append(umbc_pctchange)
    else:
        umbc_tuition_change.append(cost)
    prev_tuition = cost

umbc_tuition_change

[nan,
 nan,
 nan,
 nan,
 nan,
 7.650273224043716,
 7.648054145516074,
 16.12700408676517,
 8.554412560909583,
 6.234413965087282,
 1.1971830985915493,
 0.9974483878450475,
 0.8268259072117593,
 1.0478359908883828,
 3.370153291253381,
 3.227565151019518,
 3.1372134783986483,
 3.11347808275297,
 3.1386571315057608,
 5.989984591679507,
 2.344175904052335,
 2.254971590909091,
 2.2573363431151243]

The resulting number has many decimal points which are unnecessary and not visually appealing.
Round up the percentage to two decimal points
You can use for loop. Or better, use list comprehension for simplicity/brevity

In [ ]:
umbc_tuition_change = [round(pctchange, 2) for pctchange in umbc_tuition_change]
umbc_tuition_change

[nan,
 nan,
 nan,
 nan,
 nan,
 7.65,
 7.65,
 16.13,
 8.55,
 6.23,
 1.2,
 1.0,
 0.83,
 1.05,
 3.37,
 3.23,
 3.14,
 3.11,
 3.14,
 5.99,
 2.34,
 2.25,
 2.26]

Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")
Not as hard as you might think. If you get stuck, you're thinking too hard. 
Google it and you will find the answer.

In [ ]:
df_umbc['PCT_CHANGE'] = umbc_tuition_change
df_umbc

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



UNITID                                   INSTNM STABBR  REGION  \
2151  163268  University of Maryland-Baltimore County     MD     2.0   
2049  163268  University of Maryland-Baltimore County     MD     2.0   
1982  163268  University of Maryland-Baltimore County     MD     2.0   
1955  163268  University of Maryland-Baltimore County     MD     2.0   
1926  163268  University of Maryland-Baltimore County     MD     2.0   
1915  163268  University of Maryland-Baltimore County     MD     2.0   
1893  163268  University of Maryland-Baltimore County     MD     2.0   
1873  163268  University of Maryland-Baltimore County     MD     2.0   
1830  163268  University of Maryland-Baltimore County     MD     2.0   
1819  163268  University of Maryland-Baltimore County     MD     2.0   
1799  163268  University of Maryland-Baltimore County     MD     2.0   
1779  163268  University of Maryland-Baltimore County     MD     2.0   
1767  163268  University of Maryland-Baltimore County     MD     2.0   
1745  163268  University of Maryland-Baltimore County     MD     2.0   
1710  163268  University of Maryland-Baltimore County     MD     2.0   
1694  163268  University of Maryland-Baltimore County     MD     2.0   
1660  163268  University of Maryland-Baltimore County     MD     2.0   
1629  163268  University of Maryland-Baltimore County     MD     2.0   
1610  163268  University of Maryland-Baltimore County     MD     2.0   
1555  163268  University of Maryland-Baltimore County     MD     2.0   
1510  163268  University of Maryland-Baltimore County     MD     2.0   
1478  163268  University of Maryland-Baltimore County     MD     2.0   
1415  163268  University of Maryland-Baltimore County     MD     2.0   

      ADM_RATE  TUITIONFEE_IN  YEAR  PCT_CHANGE  
2151       NaN            NaN  1996         NaN  
2049       NaN            NaN  1997         NaN  
1982       NaN            NaN  1998         NaN  
1955       NaN            NaN  1999         NaN  
1926       NaN         5490.0  2000         NaN  
1915    0.6551         5910.0  2001        7.65  
1893    0.6327         6362.0  2002        7.65  
1873    0.5757         7388.0  2003       16.13  
1830    0.7014         8020.0  2004        8.55  
1819    0.7143         8520.0  2005        6.23  
1799    0.7153         8622.0  2006        1.20  
1779    0.6895         8708.0  2007        1.00  
1767    0.7174         8780.0  2008        0.83  
1745    0.6890         8872.0  2009        1.05  
1710    0.6589         9171.0  2010        3.37  
1694    0.6081         9467.0  2011        3.23  
1660    0.6035         9764.0  2012        3.14  
1629    0.6315        10068.0  2013        3.11  
1610    0.5961        10384.0  2014        3.14  
1555    0.5942        11006.0  2015        5.99  
1510    0.5683        11264.0  2016        2.34  
1478    0.6021        11518.0  2017        2.25  
1415    0.5794        11778.0  2018        2.26

Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [ ]:
umbc_pctchange_bar = px.bar(df_umbc,
                    x= 'YEAR',
                    y='PCT_CHANGE'
                    )

umbc_pctchange_line = px.line(df_umbc,
                    x= 'YEAR',
                    y='PCT_CHANGE'
                    )

umbc_pctchange_bar.show()
umbc_pctchange_line.show()

## <12>
Since we want to do the same calculation for JHU. 
Instead of doing it piecemeal as we did for UMBC
Let's create a function which can be reused for any college.
This function takes a list of tuitions and return a list of percentage changes year over year
This function can be used later  

In [ ]:
def pct_change(df_inst):

    tuition = df_inst['TUITIONFEE_IN'].tolist()

    prev_tuition = 0
    tuition_change = []

    for cost in tuition:
        if cost == cost:
            if prev_tuition == 0:
                prev_tuition = cost
            pctchange = ((cost - prev_tuition)/prev_tuition) * 100
            tuition_change.append(pctchange)
        else:
            tuition_change.append(cost)
        prev_tuition = cost

    tuition_change = [round(pctchange, 2) for pctchange in tuition_change]

    df_inst['PCT_CHANGE'] = tuition_change

    return df_inst

## <13>
the dataframe contains many years of data of all U.S. colleges.
let's just look at JHU
filter/query the dataframe to retrieve only rows that belong to JHU
save the JHU data to a new data frame. using a new variable 
so that the old big data frame is still available for later use.



In [ ]:
df_jhu = df.query('INSTNM == "Johns Hopkins University"')
df_jhu

UNITID                    INSTNM STABBR  REGION  ADM_RATE  \
2139  162928  Johns Hopkins University     MD     2.0       NaN   
2039  162928  Johns Hopkins University     MD     2.0       NaN   
1973  162928  Johns Hopkins University     MD     2.0       NaN   
1946  162928  Johns Hopkins University     MD     2.0       NaN   
1917  162928  Johns Hopkins University     MD     2.0       NaN   
1906  162928  Johns Hopkins University     MD     2.0    0.3431   
1884  162928  Johns Hopkins University     MD     2.0    0.3506   
1865  162928  Johns Hopkins University     MD     2.0    0.3060   
1823  162928  Johns Hopkins University     MD     2.0    0.3071   
1812  162928  Johns Hopkins University     MD     2.0    0.3509   
1792  162928  Johns Hopkins University     MD     2.0    0.2792   
1772  162928  Johns Hopkins University     MD     2.0    0.2571   
1760  162928  Johns Hopkins University     MD     2.0    0.2609   
1738  162928  Johns Hopkins University     MD     2.0    0.2782   
1703  162928  Johns Hopkins University     MD     2.0    0.2225   
1687  162928  Johns Hopkins University     MD     2.0    0.1940   
1653  162928  Johns Hopkins University     MD     2.0    0.1843   
1622  162928  Johns Hopkins University     MD     2.0    0.1813   
1603  162928  Johns Hopkins University     MD     2.0    0.1608   
1548  162928  Johns Hopkins University     MD     2.0    0.1412   
1503  162928  Johns Hopkins University     MD     2.0    0.1284   
1473  162928  Johns Hopkins University     MD     2.0    0.1254   
1410  162928  Johns Hopkins University     MD     2.0    0.1148   

      TUITIONFEE_IN  YEAR  
2139            NaN  1996  
2039            NaN  1997  
1973            NaN  1998  
1946            NaN  1999  
1917        24930.0  2000  
1906        26210.0  2001  
1884        27390.0  2002  
1865        28730.0  2003  
1823        30140.0  2004  
1812        31620.0  2005  
1792        33900.0  2006  
1772        35900.0  2007  
1760        37700.0  2008  
1738        39150.0  2009  
1703        40680.0  2010  
1687        42280.0  2011  
1653        43390.0  2012  
1622        45470.0  2013  
1603        47060.0  2014  
1548        48710.0  2015  
1503        50410.0  2016  
1473        52170.0  2017  
1410        53740.0  2018

## <14> 
Plot JHU's in-state tuition overtime from 1996 to 2019. 
Let's plot bar and line chart together

In [ ]:
jhu_instate_bar = px.bar(df_jhu,
                        x='YEAR',
                        y='TUITIONFEE_IN')
                        
jhu_instate_line = px.line(df_jhu,
                        x='YEAR',
                        y='TUITIONFEE_IN')

jhu_instate_bar.show()
jhu_instate_line.show()


## <15>
Let's calculate the JHU tuition percentge growth using the function defined earlier

In [ ]:
pct_change(df_jhu)
df_jhu

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



UNITID                    INSTNM STABBR  REGION  ADM_RATE  \
2139  162928  Johns Hopkins University     MD     2.0       NaN   
2039  162928  Johns Hopkins University     MD     2.0       NaN   
1973  162928  Johns Hopkins University     MD     2.0       NaN   
1946  162928  Johns Hopkins University     MD     2.0       NaN   
1917  162928  Johns Hopkins University     MD     2.0       NaN   
1906  162928  Johns Hopkins University     MD     2.0    0.3431   
1884  162928  Johns Hopkins University     MD     2.0    0.3506   
1865  162928  Johns Hopkins University     MD     2.0    0.3060   
1823  162928  Johns Hopkins University     MD     2.0    0.3071   
1812  162928  Johns Hopkins University     MD     2.0    0.3509   
1792  162928  Johns Hopkins University     MD     2.0    0.2792   
1772  162928  Johns Hopkins University     MD     2.0    0.2571   
1760  162928  Johns Hopkins University     MD     2.0    0.2609   
1738  162928  Johns Hopkins University     MD     2.0    0.2782   
1703  162928  Johns Hopkins University     MD     2.0    0.2225   
1687  162928  Johns Hopkins University     MD     2.0    0.1940   
1653  162928  Johns Hopkins University     MD     2.0    0.1843   
1622  162928  Johns Hopkins University     MD     2.0    0.1813   
1603  162928  Johns Hopkins University     MD     2.0    0.1608   
1548  162928  Johns Hopkins University     MD     2.0    0.1412   
1503  162928  Johns Hopkins University     MD     2.0    0.1284   
1473  162928  Johns Hopkins University     MD     2.0    0.1254   
1410  162928  Johns Hopkins University     MD     2.0    0.1148   

      TUITIONFEE_IN  YEAR  PCT_CHANGE  
2139            NaN  1996         NaN  
2039            NaN  1997         NaN  
1973            NaN  1998         NaN  
1946            NaN  1999         NaN  
1917        24930.0  2000         NaN  
1906        26210.0  2001        5.13  
1884        27390.0  2002        4.50  
1865        28730.0  2003        4.89  
1823        30140.0  2004        4.91  
1812        31620.0  2005        4.91  
1792        33900.0  2006        7.21  
1772        35900.0  2007        5.90  
1760        37700.0  2008        5.01  
1738        39150.0  2009        3.85  
1703        40680.0  2010        3.91  
1687        42280.0  2011        3.93  
1653        43390.0  2012        2.63  
1622        45470.0  2013        4.79  
1603        47060.0  2014        3.50  
1548        48710.0  2015        3.51  
1503        50410.0  2016        3.49  
1473        52170.0  2017        3.49  
1410        53740.0  2018        3.01

## <16>
Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

##### Note: this is all handeled internally in my function 'pct_change()'

## <17> 

Make a bar plot of the JHU percentage changes tuitions over time

In [ ]:
jhu_pctchange_bar = px.bar(df_jhu,
                    x= 'YEAR',
                    y='PCT_CHANGE'
                    )

jhu_pctchange_bar.show()

## <18>
In order to plot both UMBC and JHU tuition change over time in the same plot,
we need to combine the two datasets using the common key of YEAR 
First make a umbc2 dataframe with only two columns needed. WE don't need other columns.
Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge.
This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE",
We rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully,
Feel free to try it without changing the column names.

In [ ]:
df_umbc2 =df_umbc[['YEAR', 'PCT_CHANGE']]
df_umbc2.rename(columns={'PCT_CHANGE':'UMBC_PCT'}, inplace=True)
df_umbc2

/shared-libs/python3.7/py/lib/python3.7/site-packages/pandas/core/frame.py:4449: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



YEAR  UMBC_PCT
2151  1996       NaN
2049  1997       NaN
1982  1998       NaN
1955  1999       NaN
1926  2000       NaN
1915  2001      7.65
1893  2002      7.65
1873  2003     16.13
1830  2004      8.55
1819  2005      6.23
1799  2006      1.20
1779  2007      1.00
1767  2008      0.83
1745  2009      1.05
1710  2010      3.37
1694  2011      3.23
1660  2012      3.14
1629  2013      3.11
1610  2014      3.14
1555  2015      5.99
1510  2016      2.34
1478  2017      2.25
1415  2018      2.26

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns.
Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [ ]:
df_jhu2 =df_jhu[['YEAR', 'PCT_CHANGE']]
df_jhu2.rename(columns={'PCT_CHANGE':'JHU_PCT'}, inplace=True)
df_jhu2

/shared-libs/python3.7/py/lib/python3.7/site-packages/pandas/core/frame.py:4449: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



YEAR  JHU_PCT
2139  1996      NaN
2039  1997      NaN
1973  1998      NaN
1946  1999      NaN
1917  2000      NaN
1906  2001     5.13
1884  2002     4.50
1865  2003     4.89
1823  2004     4.91
1812  2005     4.91
1792  2006     7.21
1772  2007     5.90
1760  2008     5.01
1738  2009     3.85
1703  2010     3.91
1687  2011     3.93
1653  2012     2.63
1622  2013     4.79
1603  2014     3.50
1548  2015     3.51
1503  2016     3.49
1473  2017     3.49
1410  2018     3.01

Now, merge the two data frames
and display the new dataframe


In [ ]:
df_pctchg_mrgd = pd.merge(left = df_umbc2, right = df_jhu2, left_on = 'YEAR', right_on='YEAR')
df_pctchg_mrgd

YEAR  UMBC_PCT  JHU_PCT
0   1996       NaN      NaN
1   1997       NaN      NaN
2   1998       NaN      NaN
3   1999       NaN      NaN
4   2000       NaN      NaN
5   2001      7.65     5.13
6   2002      7.65     4.50
7   2003     16.13     4.89
8   2004      8.55     4.91
9   2005      6.23     4.91
10  2006      1.20     7.21
11  2007      1.00     5.90
12  2008      0.83     5.01
13  2009      1.05     3.85
14  2010      3.37     3.91
15  2011      3.23     3.93
16  2012      3.14     2.63
17  2013      3.11     4.79
18  2014      3.14     3.50
19  2015      5.99     3.51
20  2016      2.34     3.49
21  2017      2.25     3.49
22  2018      2.26     3.01

Plot UMBC and JHU separately on the same plot 
However, this does not work since the bars overlap.

In [ ]:
merged_bar = px.bar(df_pctchg_mrgd,
                    x='YEAR',
                    y=['UMBC_PCT', 'JHU_PCT']
                    )
merged_bar.show()            

Plot them together using y=\["UMBC_PCT","JHU_PCT"\] option of bar plot



In [ ]:
merged_bar = px.bar(df_pctchg_mrgd,
                    x='YEAR',
                    y=['UMBC_PCT', 'JHU_PCT'],
                    barmode='group'
                    )
merged_bar.show()            

Plot them together using y=\["UMBC_PCT","JHU_PCT"\] option of line plot


In [ ]:
merged_line = px.line(df_pctchg_mrgd,
                    x='YEAR',
                    y=['UMBC_PCT', 'JHU_PCT'],
                    )
merged_line.show()            

## <19> 
document your observation/conclusion of the comparison plots (bar/line)
use the following Markdown cell

#### Based on my observation of the plots

##### The Big Picture

- UMBC has a much greater variance in year of year precentage change for in-state tuition fees.

- In comparison JHU is much more consistent for percentage change every year.

#### The Nitty Gritty
- UMBC's greatest increase is in 2003, a whopping 16% change from the previous year. This is followed by a steady decline continuing to 2006, UMBC's smallest yearly increase during this period (1.2%). From 2010 onwards, the yearly increase remains between 3.3-2.267% with an exception noted at 2015(5.99).

- JHU, on the other hand does not reflect the same roller coaster of increases as UMBC. The early 2000's show yearly inrceases hovering around 5%. The percent change peaks during 2006 (7.21%). Thereon, the percent change remains positive but steadily decreases to 2009 (3.85%). From then on it remains fairly constant with a slight downward trajectory. There are notable exceptions in 2012 (2.63%) and 2013 (4.79%).

# The end.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0aee4006-0af7-4619-8637-ef17c840cb78' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>